"""empty message

Revision ID: 20ceed65027b
Revises: None
Create Date: 2016-06-13 16:09:13.530614

"""

# revision identifiers, used by Alembic.
revision = '20ceed65027b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('mimetype', sa.String(length=128), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    ### end Alembic commands ###
