"""empty message

Revision ID: 228faf2f9c78
Revises: None
Create Date: 2016-05-30 22:02:47.078798

"""

# revision identifiers, used by Alembic.
revision = '228faf2f9c78'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    ### end Alembic commands ###
